#!/usr/bin/env python3

import os
import sys

import lagrangians

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Usage: lagrangians <input_files>")
    else:
        for filename in sys.argv[1:]:
            lagrangian.Lagrangians(filename).run()
