#!/usr/bin/env python3

import os
import sys

import grapher
import parse

def do_image(filenames):
    for filename in filenames:
        my_grapher = grapher.Grapher(filename)
    my_grapher.do_run()

def do_video(filename):
    my_grapher = grapher.VideoGrapher(filename)
    my_grapher.do_run()

if __name__ == "__main__":
    if len(sys.argv) == 1:
        print("Usage: lagrangians <input_files>")
    else:
        for filename in sys.argv[1:]:
            if parse.is_video(filename):
                my_grapher = grapher.VideoGrapher(filename)
                my_grapher.make_movie()
            else:
                my_grapher = grapher.Grapher(filename)

#            my_grapher.do_run()
