((((Power(b,2) + Power(h,2))*Subscript(m,3))/12. + 
        Subscript(m,3)*(Power(Subscript(x,0),2) + Power(Subscript(y,0),2)))*
      Power(Subscript(\[Phi],3)(t),2))/2. + 
   (Subscript(m,2)*(Power(-(Cos(Subscript(\[Phi],2)(t))*
             Derivative(1)(Subscript(r,2))(t)) + 
          Sin(Subscript(\[Phi],2)(t))*Subscript(r,2)(t)*
           Derivative(1)(Subscript(\[Phi],2))(t) + 
          (b*Cos(Subscript(\[Phi],3)(t))*Derivative(1)(Subscript(\[Phi],3))(t))/2.,2) + 
        Power(Sin(Subscript(\[Phi],2)(t))*Derivative(1)(Subscript(r,2))(t) + 
          Cos(Subscript(\[Phi],2)(t))*Subscript(r,2)(t)*
           Derivative(1)(Subscript(\[Phi],2))(t) - 
          (b*Sin(Subscript(\[Phi],3)(t))*Derivative(1)(Subscript(\[Phi],3))(t))/2.,2)))/
    2. + (Subscript(m,1)*(Power(-(Cos(Subscript(\[Phi],1)(t))*
             Derivative(1)(Subscript(r,1))(t)) + 
          Sin(Subscript(\[Phi],1)(t))*Subscript(r,1)(t)*
           Derivative(1)(Subscript(\[Phi],1))(t) - 
          (b*Cos(Subscript(\[Phi],3)(t))*Derivative(1)(Subscript(\[Phi],3))(t))/2.,2) + 
        Power(Sin(Subscript(\[Phi],1)(t))*Derivative(1)(Subscript(r,1))(t) + 
          Cos(Subscript(\[Phi],1)(t))*Subscript(r,1)(t)*
           Derivative(1)(Subscript(\[Phi],1))(t) + 
          (b*Sin(Subscript(\[Phi],3)(t))*Derivative(1)(Subscript(\[Phi],3))(t))/2.,2)))/
    2.
